### PR TITLE
fix time for user date time string with no timezone

### PR DESCRIPTION
**Pull request by adey**

### CODE REVIEW

**Comment by idpaterson** [comment]
@adey the "Merge pull request #1 from ady624/master" ended up included in this PR. Since that references a pull request on your fork could you instead create a new branch in your repo and submit that branch as a pull request? A separate branch helps to avoid unrelated commits getting added into the pull request unintentionally, I usually use a branch name like `pull-requests/some-name` to keep them organized.

**Comment by adey** [comment]
yep … will do in a bit. sorry … should have checked.

**Comment by idpaterson** [comment]
Thanks, this was cherry-picked to the dev branch [here](https://github.com/ady624/webCoRE/commit/28ad535e52d56b3eb9204fca1bdcb7ddab8ebd24)

**Comment by adey** [comment]
thanks man. sorry for the trouble.

**Pull request closed without merging**
