### PR TITLE
Add SHM incident detection to system variables

### PR DESCRIPTION
**Pull request by green-arrow**
Addresses #18

### CODE REVIEW

**Comment by ady624** [comment]
The incidents list is an unofficial implementation of an undocumented feature. If I were to add it to webCoRE, I'd most likely make it work with $incidents which would be a JSON type, allowing for $incidents.length, $incidents[0], etc. so that one could read the actual incidents too. However, there is no "detection" mechanism - meaning that there is no event telling the piston an incident was added or removed (dismissed) - the piston would have to regularly check the variable.

**Comment by green-arrow** [comment]
Ah I see, thanks for that background. 

Do you think that incidents is something that should be provided now or would it be better to wait for the feature to become documented?

**Comment by ady624** [comment]
Implemented, thank you.

**Comment by green-arrow** [comment]
Thank you for implementing!

**Pull request closed without merging**
