### PR TITLE
Updates for HE

### PR DESCRIPTION
**Pull request by imnotbob**

### CODE REVIEW

**Comment by idpaterson** [comment]
Just to confirm, can #77 be closed? It looks like #78 might be the same thing but without the conflicting line endings but I can't tell for sure. If so that's great, I'll just close #77 and review this one.

**Comment by idpaterson** [comment]
Hmm no they're not the same, at a glance #78 includes updates for fuel streams as well. I'm going to need more to go on for these than "Updates for HE" if you would please describe what has changed.

**Comment by imnotbob** [comment]
two files are changed, I gave you two pull requests.

77 covers fuel streams
78 is for access tokens and running rules

**Comment by imnotbob** [comment]
77 is big because git wanted to fix end of lines

**Comment by imnotbob** [comment]
I have all pull requests in (3)

**Comment by idpaterson** [comment]
I need one pull request including all files that need to be changed for HE compatibility and with changes on only the lines that were intentionally modified, please. #77 and #79 are not acceptable since the diffs include thousands of line ending changes that make it impossible to determine what actually changed; please commit those files without the line ending issues to pull request #78. I provided a cleaned diff for #77 to help you out but I can't keep fielding these pull requests for individual files.

Additional commits to your patch-5 branch should automatically be included in #78.

**Pull request closed without merging**
